import { DeliveryRequest } from "@/components/RequestCard";

export const mockRequests: DeliveryRequest[] = [
  {
    id: "1",
    requester: "Aarav S.",
    hostel: "Hostel A",
    room: "304",
    description: "Swiggy food order — 2 biryanis",
    reward: 30,
    arrivalTime: "12:45 PM",
    status: "pending",
    createdAt: "2 min ago",
  },
  {
    id: "2",
    requester: "Priya K.",
    hostel: "Hostel C",
    room: "112",
    description: "Amazon parcel — small box",
    reward: 25,
    arrivalTime: "1:15 PM",
    status: "pending",
    createdAt: "8 min ago",
  },
  {
    id: "3",
    requester: "Rohan M.",
    hostel: "Hostel B",
    room: "207",
    description: "Zomato order — pizza & drinks",
    reward: 40,
    arrivalTime: "1:30 PM",
    status: "accepted",
    createdAt: "15 min ago",
  },
  {
    id: "4",
    requester: "Sneha D.",
    hostel: "Hostel A",
    room: "419",
    description: "Flipkart delivery — phone cover",
    reward: 20,
    arrivalTime: "2:00 PM",
    status: "pending",
    createdAt: "22 min ago",
  },
  {
    id: "5",
    requester: "Vikram T.",
    hostel: "Hostel D",
    room: "105",
    description: "Blinkit groceries — 3 bags",
    reward: 50,
    arrivalTime: "3:00 PM",
    status: "delivered",
    createdAt: "1 hr ago",
  },
];
