import type { DeliveryRequest } from "@/components/RequestCard";

export const mockRequests: DeliveryRequest[] = [
    {
        id: "1",
        requester: "Aarav Kumar",
        hostel: "Hostel A",
        room: "304",
        description: "Swiggy food order — 2 biryanis",
        reward: 30,
        arrivalTime: "1:30 PM",
        status: "pending",
        createdAt: "2 min ago",
    },
    {
        id: "2",
        requester: "Priya Sharma",
        hostel: "Hostel C",
        room: "112",
        description: "Amazon parcel — small box",
        reward: 25,
        arrivalTime: "2:00 PM",
        status: "pending",
        createdAt: "8 min ago",
    },
    {
        id: "3",
        requester: "Rahul Verma",
        hostel: "Hostel B",
        room: "208",
        description: "Zomato order — pizza & garlic bread",
        reward: 35,
        arrivalTime: "12:45 PM",
        status: "accepted",
        createdAt: "15 min ago",
    },
    {
        id: "4",
        requester: "Sneha Patel",
        hostel: "Hostel D",
        room: "420",
        description: "Flipkart delivery — electronics",
        reward: 40,
        arrivalTime: "3:15 PM",
        status: "delivered",
        createdAt: "1 hr ago",
    },
    {
        id: "5",
        requester: "Vikram Singh",
        hostel: "Hostel A",
        room: "119",
        description: "Dunzo pickup — medicines",
        reward: 20,
        arrivalTime: "4:00 PM",
        status: "pending",
        createdAt: "5 min ago",
    },
];
